services:
  employees-calendar-web:
    container_name: employees-calendar-web
    build:
      context: ./docker/ngnix
      args:
        - UID=${UID}
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - employees-calendar-api
    networks:
      - employees-calendar-network

  employees-calendar-api:
    container_name: employees-calendar-api
    build:
      context: ./docker/php
      args:
        UID: ${UID}
    environment:
      PHP_IDE_CONFIG: "serverName=employees-calendar.local"
      PHP_XDEBUG_ENABLED: '1'
      XDEBUG_CONFIG: remote_host=host.docker.internal
    ports:
      - "${PHP_PORT:-9000}:9000"
      - "${XDEBUG_PORT:-9005}:${XDEBUG_PORT:-9005}"
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ${HOME}/.ssh/id_rsa:/home/appuser/.ssh/id_rsa:ro
    depends_on:
      - employees-calendar-db
    networks:
      - employees-calendar-network

  employees-calendar-db:
    container_name: employees-calendar-db
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-employees_calendar}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_PASSWORD:-root}
    volumes:
      - employees-calendar-db-data:/var/lib/postgresql/data
    networks:
      - employees-calendar-network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  employees-calendar-db-data: {}

networks:
  employees-calendar-network:
    external: true